services:
  tilearchive:
    image: ethanmitchell9/mariadb:latest # Added docker server (changing this to allow push to my account ethanmitchell9)
    #container_name: tilearchive-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - tile-volume:/var/lib/mysql
      - ./DatabaseNearFinal.sql:/docker-entrypoint-initdb.d/DatabaseNearFinal.sql
    networks:
      - ceramnote

  ceramnote:
    build: ./frontend # changed to frontend; added build command
    image: ethanmitchell9/ceramnote:latest
    #container_name: ceramnote-container
    ports:
      - "80:80"
    depends_on:
      - tilearchive
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/data
    networks: # Added
      - ceramnote # Added

  backend:
    build: ./backend # changed to backend
    image: ethanmitchell9/backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    depends_on:
      - tilearchive
    networks: # Added
      - ceramnote #added

volumes:
  tile-volume:
  data-volume:

# Added all of this
networks:
  ceramnote:
    driver: bridge
